# Generated by Django 6.0.2 on 2026-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_slash_command_drop_unique_add_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='claude_in_chrome',
            field=models.BooleanField(default=False),
        ),
    ]
