# Generated by Django 6.0.2 on 2026-03-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_session_claude_in_chrome'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='search_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
