# Generated by Django 6.0.2 on 2026-04-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_backfill_search_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='keep_settings',
            field=models.BooleanField(default=False),
        ),
    ]
